FROM python:3.14-alpine
WORKDIR /task_app

COPY . .


RUN apk add --no-cache \
    postgresql-client \
    postgresql-dev \
    gcc \
    python3-dev \
    musl-dev && \
    pip3 install uv && \
    uv sync


RUN chmod +x docker-entrypoint.prod.sh 

EXPOSE 5556

ENTRYPOINT ["./docker-entrypoint.prod.sh"]


