services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
       - ./migrations:/task_app/migrations
       - ./emergency_fallback.jsonl:/task_app/emergency_fallback.jsonl
    # cap_add:
    #   - SYS_PTRACE
    # The ports mapping, that your application needed when you start
    ports:
      - "127.0.0.1:5556:5555" 
    
    restart: always
    # All your required elements are in the .env so you load that
    env_file:
      - .env
    # We now pass the DB_* variables directly, matching the config.py.
    environment:
      DB_HOST: prod-db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    
    depends_on:
      prod-db:
        condition: service_healthy

      redis:
        condition: service_started 
      
      prometheus:
        condition: service_started

    # It is a little bit interesting section, like whenever you make changes in the code in the file, and compose watch catches that it rebuilds the image
    # Sometimes it reloads the container
    develop:
      watch:
        - action: rebuild
          path: .
          target: /task_app
          ignore:
            - .venv/
            - .git/
            - .egg-info/
            - __pycache__

    # This command runs the database migrations first, then starts the application.
    # command: sh -c "flask --app run.py db upgrade && uv run python run.py"

    entrypoint: ./docker-entrypoint.prod.sh



#####

  prod-db:
    image: postgres:17

    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - task_app_data:/var/lib/postgresql/data
  
    shm_size: '2gb'
    
    command: >
      postgres 
      -c shared_buffers=1GB 
      -c max_wal_size=2GB 
      -c min_wal_size=512MB 
      -c checkpoint_timeout=15min
      -c maintenance_work_mem=512MB
      -c synchronous_commit=off

    deploy:
      resources:
        limits: 
          memory: 2GB
    
    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}  -d ${DB_NAME} "]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

    restart: always



####

  go-batcher:
    build:
      context: ../batch_processing
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:7676:7676"
      - "127.0.0.1:6060:6060"

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DATABASE_URL: postgres://task_user:${DB_PASSWORD}@prod-db:5432/${DB_NAME}
    
    depends_on:
      prod-db:
        condition: service_healthy

    restart: always


##### 

  redis:
    image: redis:8.2
    # container_name: redis_server
    ports: 
      - "6380:6379"

    restart: always
    volumes:
      - redis_data:/data 

    command: ["redis-server","--maxmemory","2gb", "--appendonly", "yes","--requirepass","${REDIS_PASSWORD}"]

####

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml # in this there is no write is happening just being used by the prometheus-server
      - ./prometheus_data_prod:/prometheus # for this container need write permission (since it is bind mount host folder should have the permission for other 777)

    restart: always
    command:
      - --storage.tsdb.path=/prometheus
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"



####

  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - "3000:3000"




volumes:
  task_app_data:
    name: task_app_data 
  redis_data:
    name: redis_data

