services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
       - ./migrations:/task_app/migrations
       - ./emergency_fallback.jsonl:/task_app/emergency_fallback.jsonl
    cap_add:
      - SYS_PTRACE
    # The ports mapping, that your application needed when you start
    ports:
      - "127.0.0.1:5555:5555" 
    
    # All your required elements are in the .env so you load that
    env_file:
      - .env
    # We now pass the DEV_DB_* variables directly, matching the config.py.
    environment:
      DEV_DB_HOST: dev-db
      DEV_DB_USER: ${DEV_DB_USER}
      DEV_DB_PASSWORD: ${DEV_DB_PASSWORD}
      DEV_DB_NAME: ${DEV_DB_NAME}
      DEV_DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    
    depends_on:
      dev-db:
        condition: service_healthy

      redis:
        condition: service_started 
      
      prometheus:
        condition: service_started

    # It is a little bit interesting section, like whenever you make changes in the code in the file, and compose watch catches that it rebuilds the image
    # Sometimes it reloads the container
    develop:
      watch:
        - action: rebuild
          path: .
          target: /task_app
          ignore:
            - .venv/
            - .git/
            - .egg-info/
            - __pycache__

    # This command runs the database migrations first, then starts the application.
    # command: sh -c "flask --app run.py db upgrade && uv run python run.py"

    entrypoint: ./docker-entrypoint.dev.sh


  go-batcher:
    build:
      context: ../batch_processing
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:7676:7676"
      - "127.0.0.1:6060:6060"

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DATABASE_URL: postgres://task_dev_user:dev_secret@dev-db:5432/task_dev_db

    depends_on:
      dev-db:
        condition: service_healthy


  dev-db:
    image: postgres:17


    # build:
    #   context: .
    #   dockerfile: Dockerfile.pg.dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    volumes:
      - task_app_data:/var/lib/postgresql/data
      # This health check tells Docker Compose to wait until the database is ready
    #
    shm_size: '2gb'
    
    command: >
      postgres 
      -c shared_buffers=2GB 
      -c max_wal_size=4GB 
      -c min_wal_size=1GB 
      -c checkpoint_timeout=15min
      -c maintenance_work_mem=512MB

    deploy:
      resources:
        limits: 
          memory: 4GB
    
    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U ${DEV_DB_USER}  -d ${DEV_DB_NAME} "]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s


  redis:
    image: redis:8.2
    # container_name: redis_server
    ports: 
      - "6380:6379"

    volumes:
      - redis_data:/data 

    command: ["redis-server","--maxmemory","2gb", "--appendonly", "yes","--requirepass","${REDIS_PASSWORD}"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.dev.yml:/etc/prometheus/prometheus.yml # in this there is no write is happening just being used by the prometheus-server
      - ./prometheus_data_dev:/prometheus # for this container need write permission (since it is bind mount host folder should have the permission for other 777)
    command:
      - --storage.tsdb.path=/prometheus
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  task_app_data:
    name: task_app_data 
  redis_data:
    name: redis_data


