set_real_ip_from 127.0.0.1;
real_ip_header X-Real-IP;

map $request_method $is_read{
    GET     1;
    default 0;
}

map $request_method $is_write {
    POST    1;
    PUT     1;
    DELETE  1;
    default 0;
}


map $is_read $read_limit_key{
    1	$binary_remote_addr;
    0 			 "";
}

map $is_write $write_limit_key{
    1 $binary_remote_addr;
    0		       "";
}



limit_req_zone $write_limit_key zone=post_auth_read_limit:10m rate=60r/m;
limit_req_zone $read_limit_key zone=post_auth_write_limit:10m rate=300r/m;

# This is a pre-auth thing that is why we havent put it in the map thing 
limit_req_zone $binary_remote_addr zone=api_limit_pre_auth:10m rate=20r/m;



