upstream backend_app {
	server 127.0.0.1:5555;
	keepalive 64;
}

server {
	listen 80 default_server;
	server_name _;

	limit_req_status 429;

	location / {
	    proxy_pass http://backend_app;
	}

	location /api/v1/tasks {

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_http_version 1.1;
		proxy_set_header Connection "";
		proxy_connect_timeout 5s;
		proxy_read_timeout 30s;
		proxy_send_timeout 30s;

		proxy_buffering on;


		limit_req zone=post_auth_read_limit burst=50 nodelay ;
		limit_req zone=post_auth_write_limit burst=10 nodelay ;
	
		proxy_pass http://backend_app;
	}


	location /api/v1/auth/ {

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_http_version 1.1;
		proxy_set_header Connection "";
		proxy_connect_timeout 5s;
		proxy_read_timeout 30s;
		proxy_send_timeout 30s;

		proxy_buffering on;

		limit_req zone=api_limit_pre_auth burst=10 nodelay;
		proxy_pass http://backend_app;
	}
	
	error_page 429 = /rate_limited;

	location = /rate_limited {
    		internal;
    		default_type application/json;
    		return 429 '{"error":{"Code":"TOO_MANY_REQUEST","status":429,"message":"Rate Limit Exceeded"}';
	}

}


